name: flutter_app_component
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #下拉菜单
  jd_dropdowm_menu_widget: any
  #popwindow
  popup_window: ^1.1.1
  iconfont_dart: ^0.3.3
  color_dart: ^0.2.1
  # 状态管理
  provider: ^4.1.2

  #持久化数据库
  shared_preferences: ^0.5.8

  jd_home:
    path: ../jd_home

  jd_core:
    path: ../jd_core
  #保存图片
#  albumsaver:
#    git:
#      url: https://github.com/JDongKhan/flutter_plugin.git
#      #      ref:some-branch
#      path: album_saver



#  json_to_model: ^1.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  device_preview: ^0.5.5
  flutter_smart_dialog: any
  link_scroll_menu: any
  azlistview: any
  lpinyin: any
  #应用信息
  package_info: ^0.4.1
  #因为单词
  english_words: ^3.1.5
  #相册
  image_picker: ^0.6.6
#  photo: ^0.4.8
  #wechat_assets_picker: ^6.0.1

  #二维码
  qr_flutter: ^3.1.0

  #网络图片库
  cached_network_image: ^2.2.0

  stacked_card_carousel: ^0.0.2+1
  get: 4.1.4
  #logger
  logger: ^1.0.0
  sensors: ^2.0.3
#  logger_flutter: ^0.7.1
  #大图预览
  photo_view: ^0.10.1

  # 走马灯
  marquee: ^2.1.0
  # 视频播放
  #fijkplayer: ^0.8.3
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.24.1
  #国际化
  #  fluintl: ^0.1.3


  #fish_redux
  fish_redux: ^0.3.4
  #html
#  flutter_html:  2.0.0
  #链式编程
  widget_chain: ^0.1.0
  #升级
  flutter_app_upgrade: ^1.1.0
  flutter_slidable: any

  camera: ^0.5.8+2
  video_player: ^2.1.6

  #extended_nested_scroll_view: ^1.0.0
  #瀑布流
  flutter_staggered_grid_view: ^0.4.0

  #bugly
  flutter_bugly: ^0.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 图标库
  cupertino_icons: ^1.0.0
  badges: ^2.0.1

  lifecycle: 0.2.0

  simple_animations: 2.4.2
#  flutterlifecyclehooks: 1.0.1
  tableview: ^0.0.3

#  leak_detector: ^1.0.1+3

#  dokit: ^0.6.1


#  flutter_tencentplayer_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#ume
  flutter_ume: ^0.1.0
  flutter_ume_kit_ui: ^0.1.0
  flutter_ume_kit_device: ^0.1.0
  flutter_ume_kit_perf: ^0.1.0
  flutter_ume_kit_show_code: ^0.1.0
  flutter_ume_kit_console: ^0.1.0

#  build_runner: ^1.10.1
#  json_serializable: ^3.2.5
#  json_annotation: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

dependency_overrides:
  platform: ^3.0.0
  device_info: ^1.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/data/
    - assets/icons/
    - assets/videos/
    - assets/images/
#    - assets/images/3.0x/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
