name: flutter_component
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
#https://pub.dev/packages/
#https://pub.flutter-io.cn

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #保存图片
  albumsaver:
    git:
      url: https://github.com/JDongKhan/flutter_plugin.git
      path: album_saver

  json_to_model: ^1.3.13
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 图标库
  cupertino_icons: ^0.1.2
  #应用信息
  package_info: ^0.4.1
  #因为单词
  english_words: ^3.1.5
  #相册
  image_picker: ^0.6.6
  #打开第三方应用
  url_launcher: 5.4.2
  #网络
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  #path
  path_provider: ^1.6.9
  #二维码
  qr_flutter: ^3.1.0
  #获取权限
  permission_handler: ^3.0.1
  #webview
  webview_flutter: ^0.3.19+8
  #设备版本信息
  device_info: '>=0.4.1+5 <2.0.0'
  #下拉刷新
  pull_to_refresh: ^1.5.8
  #Swiper库
  flutter_swiper: 1.1.6
  #网络图片库
  cached_network_image: ^2.2.0
  #持久化数据库
  shared_preferences: 0.5.6+2
  #本地json对象存储
  localstorage: ^2.0.0
  #网络状态监听
  connectivity: 0.4.8+1
  #大图预览
  photo_view: ^0.9.2
  #toask
  fluttertoast: ^4.0.0
  # 屏幕适配
  flutter_screenutil: ^1.1.0
  # 视频播放
  #fijkplayer: ^0.8.3
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.23.1
  #国际化
#  fluintl: ^0.1.3
  # 分享
  share: ^0.6.4+1
  # 状态管理
  provider: ^4.1.2
  #html
  flutter_html: ^ 1.0.0
  #链式编程
  widget_chain: ^0.1.0
  #升级
  flutter_app_upgrade: ^1.0.2
  #闪光
  shimmer: ^1.0.0

  camera: ^0.5.8+2
  video_player: '>=0.10.11+1 <2.0.0'

  extended_nested_scroll_view: ^1.0.0
  #瀑布流
  flutter_staggered_grid_view: ^0.3.0
  #进度指示器
  flutter_spinkit: "^4.1.2"
  #bugly
  flutter_bugly: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/images/
    - assets/images/splash_bg.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
