name: jd_core
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #网络
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0

  #网络请求
  http: ^0.12.2
  #网络图片库
  cached_network_image: ^2.2.0

  #打开第三方应用
  url_launcher: 5.5.0
  #path
  path_provider: ^1.6.9
  #获取权限
  permission_handler: ^5.0.1
  #设备版本信息
  device_info: '>=0.4.1+5 <2.0.0'
  #持久化数据库
  shared_preferences: ^0.5.8
  #本地json对象存储
  localstorage: ^3.0.2+5
  #网络状态监听
  connectivity: ^0.4.9
  #toask
  fluttertoast: ^7.0.2
  # 屏幕适配
  flutter_screenutil: ^5.0.0+2
  #进度指示器
  flutter_spinkit: ^4.1.2
  # 状态管理
  provider: ^4.1.2
 #下拉刷新
  pull_to_refresh: 1.6.4
  #闪光
  shimmer: ^1.0.0
  # 分享
  share: ^0.6.4+1
  #webview
  webview_flutter: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

 assets:
   - assets/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
